import { Building2, Mail, MessageSquare, Send } from "lucide-react";
import { useState } from "react";
import Navbar from "../components/Navbar";

export default function Contact() {
  const [sent, setSent] = useState(false);
  return (
    <div className="min-h-screen bg-slate-50 text-slate-950"><Navbar /><main className="px-6 py-16 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]">
      <div><div className="inline-flex items-center gap-2 rounded-full bg-orange-50 px-4 py-2 text-sm font-bold text-orange-600"><MessageSquare className="h-4 w-4" /> Contact Bouwiser</div><h1 className="mt-6 text-5xl font-black tracking-tight">Questions, feedback or partnership interest?</h1><p className="mt-5 text-lg leading-8 text-slate-600">We welcome feedback from homeowners, suppliers, manufacturers and renovation professionals.</p><div className="mt-8 space-y-4"><div className="flex items-center gap-3 rounded-2xl bg-white p-5 shadow-sm"><Mail className="h-5 w-5 text-orange-500" /><span className="font-bold">Bouwiser contact channel</span></div><div className="flex items-center gap-3 rounded-2xl bg-white p-5 shadow-sm"><Building2 className="h-5 w-5 text-orange-500" /><span className="font-bold">Supplier & partner enquiries</span></div></div></div>
      <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="rounded-[32px] border border-slate-200 bg-white p-8 shadow-xl"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Name<input required className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-orange-400" /></label><label className="text-sm font-bold">Email<input required type="email" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-orange-400" /></label></div><label className="mt-5 block text-sm font-bold">Subject<input required className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-orange-400" /></label><label className="mt-5 block text-sm font-bold">Message<textarea required rows={6} className="mt-2 w-full rounded-xl border border-slate-200 p-4 outline-none focus:border-orange-400" /></label>{sent && (<div className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">Thank you. This prototype form is ready for backend connection.</div>)}<button type="submit" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-6 py-3 font-bold text-white hover:bg-orange-600">Send message <Send className="h-4 w-4" /></button></form>
    </div></main></div>
  );
}
